blank_issues_enabled: false
contact_links:
  - name: TwitchIO Documentation
    url: https://twitchio.dev/en/latest/index.html
    about: Official TwitchIO documentation - please check here before opening an issue.
  - name: Discord
    url: https://discord.gg/RAKc3HF
    about: Join our Discord community to chat or receive help, or get in touch with the maintainers.
